#PBS -P zk16
#PBS -q normal
#PBS -l walltime=04:00:00,mem=180GB
#PBS -l ncpus=12
#PBS -l storage=gdata/zk16+scratch/zk16
#PBS -l wd
#PBS -N linkpeaks_filtered
#PBS -o /g/data/zk16/muqing/repos/hybrid_multiome/gadi/output
#PBS -e /g/data/zk16/muqing/repos/hybrid_multiome/gadi/error

module purge
module load gcc/14.2.0
module load R/4.4.2
export LD_LIBRARY_PATH=/apps/gcc/14.2.0/lib64:${LD_LIBRARY_PATH}

CONFIG_JSON=${CONFIG_JSON:-/g/data/zk16/muqing/repos/ASPEN-GLM/scripts/run_linkpeaks_filtered_config.json}

Rscript /g/data/zk16/muqing/repos/ASPEN-GLM/scripts/run_linkpeaks_filtered.R "${CONFIG_JSON}"
